"""add status_message_id and message_count_at_start to Generation

Revision ID: 996b4578735e
Revises: b98217943cba
Create Date: 2026-01-13 17:08:51.090911

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "996b4578735e"
down_revision: str | None = "b98217943cba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generations",
        sa.Column("status_message_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "generations",
        sa.Column("message_count_at_start", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generations", "message_count_at_start")
    op.drop_column("generations", "status_message_id")
    # ### end Alembic commands ###
