"""remove message_count_at_start from Generation

Revision ID: fe0a468dd084
Revises: 996b4578735e
Create Date: 2026-01-13 17:31:26.747196

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe0a468dd084"
down_revision: str | None = "996b4578735e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generations", "message_count_at_start")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generations",
        sa.Column(
            "message_count_at_start",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
