"""move status_message_id to conversation

Revision ID: 8f3b6646348c
Revises: fe0a468dd084
Create Date: 2026-01-13 17:55:45.263587

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f3b6646348c"
down_revision: str | None = "fe0a468dd084"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("status_message_id", sa.Integer(), nullable=True),
    )
    op.drop_column("generations", "status_message_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generations",
        sa.Column(
            "status_message_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("conversations", "status_message_id")
    # ### end Alembic commands ###
