"""add placeholder_message_id to generation

Revision ID: 4d4399066e95
Revises: 8f3b6646348c
Create Date: 2026-01-13 18:46:18.252906

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d4399066e95"
down_revision: str | None = "8f3b6646348c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generations",
        sa.Column("placeholder_message_id", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generations", "placeholder_message_id")
    # ### end Alembic commands ###
