"""refactor message storage

Revision ID: 5d4d4ea2024b
Revises: 4d4399066e95
Create Date: 2026-01-14 13:55:23.953353

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d4d4ea2024b"
down_revision: str | None = "4d4399066e95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "message_history_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    op.add_column(
        "conversations",
        sa.Column(
            "user_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.drop_column("conversations", "messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "messages",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("conversations", "user_prompt")
    op.drop_column("conversations", "message_history_json")
    # ### end Alembic commands ###
