"""add usage tracking to generations

Revision ID: 09120e5c74ef
Revises: 5d4d4ea2024b
Create Date: 2026-01-14 16:42:46.609895

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09120e5c74ef"
down_revision: str | None = "5d4d4ea2024b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generations",
        sa.Column("cached_input_tokens", sa.Integer(), nullable=True),
    )
    op.add_column(
        "generations",
        sa.Column("uncached_input_tokens", sa.Integer(), nullable=True),
    )
    op.add_column(
        "generations", sa.Column("output_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "generations",
        sa.Column(
            "provider_response_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "generations",
        sa.Column(
            "log_url",
            sa.String(length=2083),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generations", "log_url")
    op.drop_column("generations", "provider_response_id")
    op.drop_column("generations", "output_tokens")
    op.drop_column("generations", "uncached_input_tokens")
    op.drop_column("generations", "cached_input_tokens")
    # ### end Alembic commands ###
