"""add cost field to generations

Revision ID: 81ae04179e4e
Revises: 09120e5c74ef
Create Date: 2026-01-14 17:01:36.409481

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81ae04179e4e"
down_revision: str | None = "09120e5c74ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("generations", sa.Column("cost", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generations", "cost")
    # ### end Alembic commands ###
