"""rename cost to cost_usd

Revision ID: 43107e1e9752
Revises: 81ae04179e4e
Create Date: 2026-01-14 17:06:08.351736

"""

from typing import Sequence  # noqa: UP035

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43107e1e9752"
down_revision: str | None = "81ae04179e4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("generations", "cost", new_column_name="cost_usd")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("generations", "cost_usd", new_column_name="cost")
    # ### end Alembic commands ###
