"""add last_response_id to conversations

Revision ID: 715ddef96172
Revises: 43107e1e9752
Create Date: 2026-01-14 22:04:23.331938

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "715ddef96172"
down_revision: str | None = "43107e1e9752"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "last_response_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "last_response_id")
    # ### end Alembic commands ###
