"""add last_responses_api_response_id to conversation

Revision ID: 24102dcf243e
Revises: 331fc806656c
Create Date: 2026-01-14 23:32:57.164028

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24102dcf243e"
down_revision: str | None = "331fc806656c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "last_responses_api_response_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "last_responses_api_response_id")
    # ### end Alembic commands ###
