"""add history

Revision ID: 6264e8b27c23
Revises: 24102dcf243e
Create Date: 2026-01-15 12:43:40.517271

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6264e8b27c23"
down_revision: str | None = "24102dcf243e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "history")
    # ### end Alembic commands ###
