"""Rename history to message_history and ditch legacy

Revision ID: 573c7601aaa4
Revises: 019_populate_history_for_legacy
Create Date: 2026-01-15 15:51:31.561689

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "573c7601aaa4"
down_revision: str | None = "019_populate_history_for_legacy"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversations", "history", new_column_name="message_history"
    )
    op.drop_column("conversations", "message_history_json")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "message_history_json",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "conversations", "message_history", new_column_name="history"
    )
    # ### end Alembic commands ###
