"""add started_at to generations

Revision ID: 432253f512f4
Revises: 573c7601aaa4
Create Date: 2026-01-15 21:27:21.124202

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "432253f512f4"
down_revision: str | None = "573c7601aaa4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generations",
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###

    # Manual data backfill for historical data
    op.execute("""
        UPDATE generations
        SET started_at = scheduled_for
        WHERE status IN ('started', 'completed', 'failed')
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generations", "started_at")
    # ### end Alembic commands ###
