"""add match_id to generations table

Revision ID: 010faae6c735
Revises: f205b3c04a16
Create Date: 2026-02-06 02:36:04.757656

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "010faae6c735"
down_revision: str | None = "f205b3c04a16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generations", sa.Column("match_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        "fk_generations_match_id_matches",
        "generations",
        "matches",
        ["match_id"],
        ["id"],
    )
    # ### end Alembic commands ###

    # Add CHECK constraint: exactly one of conversation_id or match_id must be set
    op.create_check_constraint(
        "ck_generations_one_task_type",
        "generations",
        "(conversation_id IS NOT NULL AND match_id IS NULL) OR (conversation_id IS NULL AND match_id IS NOT NULL)",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_generations_one_task_type", "generations", type_="check"
    )
    op.drop_constraint(
        "fk_generations_match_id_matches", "generations", type_="foreignkey"
    )
    op.drop_column("generations", "match_id")
    # ### end Alembic commands ###
