"""add latest_profile_updated_at to matches

Revision ID: b57860ec7506
Revises: 5b1091d18e36
Create Date: 2026-02-07 00:35:37.132643

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b57860ec7506"
down_revision: str | None = "5b1091d18e36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable
    op.add_column(
        "matches",
        sa.Column(
            "latest_profile_updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    # Backfill existing real matches (where user_b_id is not null): use created_at as conservative fallback
    # This prevents immediately re-matching all existing pairs
    # Unmatched records (user_b_id IS NULL) keep latest_profile_updated_at as NULL
    op.execute(
        text("""
        UPDATE matches
        SET latest_profile_updated_at = created_at
        WHERE user_b_id IS NOT NULL
          AND latest_profile_updated_at IS NULL
        """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "latest_profile_updated_at")
    # ### end Alembic commands ###
