"""add_flags_to_users

Revision ID: d74864c85d47
Revises: b2d4f6a8c029
Create Date: 2026-02-16 14:48:59.562450

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d74864c85d47"
down_revision: str | None = "b2d4f6a8c029"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "flags",
            JSONB(),
            server_default="[]",
            nullable=False,
        ),
    )
    op.create_index(
        "ix_users_flags",
        "users",
        ["flags"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_flags", table_name="users", postgresql_using="gin")
    op.drop_column("users", "flags")
    # ### end Alembic commands ###
