"""rename source_message_id to thread_id in announces

Revision ID: 52ba52d1b638
Revises: a3dc5659eb5e
Create Date: 2026-02-16 22:13:55.109389

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52ba52d1b638"
down_revision: str | None = "a3dc5659eb5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("TRUNCATE announces CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announces", sa.Column("thread_id", sa.BigInteger(), nullable=False)
    )
    op.drop_constraint(
        op.f("announces_source_message_id_key"), "announces", type_="unique"
    )
    op.create_unique_constraint(
        "announces_thread_id_key", "announces", ["thread_id"]
    )
    op.drop_column("announces", "source_message_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announces",
        sa.Column(
            "source_message_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("announces_thread_id_key", "announces", type_="unique")
    op.create_unique_constraint(
        op.f("announces_source_message_id_key"),
        "announces",
        ["source_message_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("announces", "thread_id")
    # ### end Alembic commands ###
