"""add system_message to announcements

Revision ID: c7553ed2a5ea
Revises: a3f7c2d15e89
Create Date: 2026-02-18 02:40:34.333887

"""

from typing import Sequence  # noqa: UP035

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7553ed2a5ea"
down_revision: str | None = "a3f7c2d15e89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements", sa.Column("system_message", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("announcements", "system_message")
    # ### end Alembic commands ###
