"""add username to users

Revision ID: de4f4361ff52
Revises: c7553ed2a5ea
Create Date: 2026-02-19 18:10:57.270012

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de4f4361ff52"
down_revision: str | None = "c7553ed2a5ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("username", sa.VARCHAR(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    # ### end Alembic commands ###
