"""add omit_pitch_in_instructions to chat

Revision ID: f6a920278d9a
Revises: de4f4361ff52
Create Date: 2026-02-25 11:48:41.446529

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6a920278d9a'
down_revision: str | None = 'de4f4361ff52'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('omit_pitch_in_instructions', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'omit_pitch_in_instructions')
    # ### end Alembic commands ###

