"""add_ondelete_constraints_to_all_foreign_keys

Revision ID: 63b2bc035f06
Revises: f6a920278d9a
Create Date: 2026-03-02 17:24:13.224336

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63b2bc035f06"
down_revision: str | None = "f6a920278d9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("announces_group_id_fkey"), "announcements", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("announces_group_id_fkey"),
        "announcements",
        "user_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("conversations_telegram_id_fkey"), "chats", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("conversations_telegram_id_fkey"),
        "chats",
        "users",
        ["telegram_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_generations_match_id_matches"),
        "generations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("generations_chat_id_fkey"), "generations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("generations_chat_id_fkey"),
        "generations",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_generations_match_id_matches"),
        "generations",
        "matches",
        ["match_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("matches_user_b_id_fkey"), "matches", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("matches_user_a_id_fkey"), "matches", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("matches_user_b_id_fkey"),
        "matches",
        "users",
        ["user_b_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("matches_user_a_id_fkey"),
        "matches",
        "users",
        ["user_a_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("user_group_members_user_id_fkey"),
        "user_group_members",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("user_group_members_user_id_fkey"),
        "user_group_members",
        "users",
        ["user_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        "user_group_members_user_id_fkey",
        "user_group_members",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("user_group_members_user_id_fkey"),
        "user_group_members",
        "users",
        ["user_id"],
        ["telegram_id"],
    )
    op.drop_constraint("matches_user_b_id_fkey", "matches", type_="foreignkey")
    op.drop_constraint("matches_user_a_id_fkey", "matches", type_="foreignkey")
    op.create_foreign_key(
        op.f("matches_user_a_id_fkey"),
        "matches",
        "users",
        ["user_a_id"],
        ["telegram_id"],
    )
    op.create_foreign_key(
        op.f("matches_user_b_id_fkey"),
        "matches",
        "users",
        ["user_b_id"],
        ["telegram_id"],
    )
    op.drop_constraint(
        "generations_match_id_fkey", "generations", type_="foreignkey"
    )
    op.drop_constraint(
        "generations_chat_id_fkey", "generations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("generations_chat_id_fkey"),
        "generations",
        "chats",
        ["chat_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_generations_match_id_matches"),
        "generations",
        "matches",
        ["match_id"],
        ["id"],
    )
    op.drop_constraint("chats_telegram_id_fkey", "chats", type_="foreignkey")
    op.create_foreign_key(
        op.f("conversations_telegram_id_fkey"),
        "chats",
        "users",
        ["telegram_id"],
        ["telegram_id"],
    )
    op.drop_constraint(
        "announcements_group_id_fkey", "announcements", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("announces_group_id_fkey"),
        "announcements",
        "user_groups",
        ["group_id"],
        ["id"],
    )
