"""fix_generation_fks_to_cascade

Revision ID: 6991d7de6488
Revises: 63b2bc035f06
Create Date: 2026-03-02 17:27:40.202288

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6991d7de6488"
down_revision: str | None = "63b2bc035f06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("generations_chat_id_fkey"), "generations", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_generations_match_id_matches", "generations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("generations_match_id_fkey"),
        "generations",
        "matches",
        ["match_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("generations_chat_id_fkey"),
        "generations",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        "generations_match_id_fkey", "generations", type_="foreignkey"
    )
    op.drop_constraint(
        "generations_chat_id_fkey", "generations", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_generations_match_id_matches",
        "generations",
        "matches",
        ["match_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("generations_chat_id_fkey"),
        "generations",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="SET NULL",
    )
