"""add cv fields to users

Revision ID: c917afd58f41
Revises: 6991d7de6488
Create Date: 2026-03-03 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c917afd58f41'
down_revision: str | None = '6991d7de6488'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cv_text', sa.Text(), nullable=True))
    op.add_column(
        'users', sa.Column('cv_uploaded_at', sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cv_uploaded_at')
    op.drop_column('users', 'cv_text')
    # ### end Alembic commands ###
